### PR TITLE
🔍 Added Next SEO

### PR DESCRIPTION
**Pull request by max-programming**

### CODE REVIEW

**Comment by janaSunrise** [comment]
Hi there! Thank you for the PR!

I have a question, Isn't `_document.jsx` necessary? It not only had the `Meta` component, but also the Favicon too.

Reference: https://github.com/janaSunrise/nextjs-quickstart-template/blob/main/pages/_document.jsx#L15

**Comment by max-programming** [comment]
@janaSunrise It's not really important to add _document because the `<Head>` component by Next.js can be used anywhere easily for scripts and all that.

Putting a whole document file overriding the default document is not necessary but you can put it up if you want.

The favicon is also added in the SEO component in _app

**Comment by janaSunrise** [comment]
Yeah, I agree. Just wanted to follow the necessary rules and things, as everyone does, haha.

**Comment by max-programming** [comment]
I guess it's time to merge 😉

**Comment by janaSunrise** [comment]
Hi there! I suggest re-locking with a higher version of node, Possibly v14 or above. The lockfile is v1 currently, but I think v2 should be the version, because it's latest and up-to-date one. Once done, I'll merge!

Sorry for the delay too 😅

**Pull request merged**
